[templates]
    [templates.myJavaScriptTemplate]
        path = "javascript"
        main = "src/lib.js"
        lang = "javascript"
        api_version = "0.16.3"

    [templates.myTinyGoTemplate]
        path = "tinygo"
        main = "main.go"
        lang = "tinygo"
        api_version = "0.16.3"

    [templates.wasmlab]
        path = "python"
        main = "main.py"
        lang = "python"
        api_version = "0.16.3"
